### ISSUE TITLE
Remove JSONDecoder

### ISSUE THREAD

**Issue by EmreTech** [Pycord-Development/pycord-v3#83]
Currently, in the `pycord.api` module, there is a class named `JSONDecoder` that does nothing but wrap `utils.loads`:

https://github.com/Pycord-Development/pycord-v3/blob/e1742c0d9d41e892abfa59879e8ace0ba0bdaba5/pycord/api/json_decoder.py#L28-L36

This is not needed because [`aiohttp.ClientResponse.json`](https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientResponse.json) accepts any function-like object for the `loads` parameter, as used here:

https://github.com/Pycord-Development/pycord-v3/blob/ee065f5bee52e7067dfbfcdda0837355a011ce19/pycord/utils.py#L42-L45

**Comment by Om1609** [comment]
What about using orjson? That's supposedly a lot faster as it is in Rust

**Comment by EmreTech** [comment]
I said nothing about using json or orjson. All I said was to get rid of the `JSONDecoder` class because it's useless.

**Comment by Om1609** [comment]
Sorry I thought JSONDecoder handles the decoding of `orjson.dumps` but that's not true. 
You need to do something like-
```py
http_session = aiohttp.ClientSession(json_serialize=lambda x: orjson.dumps(x).decode())
```
Like you mentioned on the discord server, that is actually done with `utils.dumps`, and JSONDecoder doesn’t play a part in it.

**Comment by VincentRPS** [comment]
> Sorry I thought JSONDecoder handles the decoding of `orjson.dumps` but that's not true. You need to do something like-
> 
> ```python
> http_session = aiohttp.ClientSession(json_serialize=lambda x: orjson.dumps(x).decode())
> ```
> 
> Like you mentioned on the discord server, that is actually done with `utils.dumps`, and JSONDecoder doesn’t play a part in it.

Currently utils.dumps uses json with the msgspec library being the optional speed dep since it's faster than orjson
